
<h3>Cell Tower</h3>
<img class="right" width="60%" src="/images/solar-powered-cell-antenna-1.jpg" />
<p>
	<strong>June 5th, 2014</strong><br />
	The towers themselves have been updated to new steel posts, and have been repositioned for better reception. Currently the repeater installed only allows one carrier (Verizon) and one band (4gLte).  We are raising the $900.00 USD to purchase a multi-band repeater (<a href="http://www.amazon.com/Wilson-Electronics-461104-Signal-Booster/dp/B00IQF4TTY#" target="_blank">This One</a>) and more towers/antennas to provide consistent cell service to everyone at the base for any carrier.
</p>
<div class="clearall"></div>
<hr />