
<h3>Tiny House</h3>
<img src="/images/living-tiny/Tiny-Smart-House-Small.jpg" class="right" width="60%" />
<p>
	<strong>July 23rd, 2014</strong><br />
	Everything is put back together and painted and we are moving forward on our decision to sell the place.  It has been very hard for Rachel and I to decide to let go of yet another home.  However we feel that God is using this as an open window to free us from the medical bills we have left and launch us into missions.  Since we have put it up for sale we have had quite a few people interested in it.  We are excited to see the next step. 
</p>
<p>
	<strong>July 13th, 2014</strong><br />
	We just finished putting on the siding, putting up the sheetrock, and mudding the interior, another few hours labor and our beautiful tiny home will be habitable once again. 
</p>
<p>
	<strong>June 6th, 2014</strong><br />
	We are currently trying to sell our tiny home on a trailer that God has blessed us with and enabled us to live in.  We have learned a lot living in such a small space with so little.  We have posted the house on Craig's List, you can see it here <a href="http://sfbay.craigslist.org/nby/rvs/4553379568.html" target="_blank">here</a>.  If you know anyone who is interested please <a href="/default.asp?content=contact">contact us</a>
</p>
<div class="clearall"></div>
<hr />