<div id="header">
	<img src="/images/Newsletter-Header-YWAM-Chico-header.jpg" />
</div>

<div id="navBar">
	<a id="logo">
		<img src="/images/Ruda-Brand-Logo.png" />
	</a>
	<ul class="nav medWidth">
		<li>
			<a href="/">HOME</a>
		</li>
		<li>
			<a href="/default.php?content=our-story">OUR STORY</a>
		</li>
		<li>
			<a href="/default.php?content=mold-help">MOLD HELP</a>
		</li>
		<li>
			<a href="/default.php?content=living-tiny">LIVING TINY</a>
		</li>
		<li>
			<a href="/default.php?content=comingsoon">MISSONS</a>
		</li>
		<!--
		<li>
			<a href="/default.php?content=give">GIVE</a>
		</li>
		-->
		<li>
			<a href="/default.php?content=archive">ARCHIVE</a>
		</li>
	</ul>
	<ul class="nav smallWidth">
		<li>
			<a id="menuButton">MENU</a>
			<ul class="subNav smallWidth">
				<li>
					<a href="/">HOME</a>
				</li>
				<li>
					<a href="/default.php?content=our-story">OUR STORY</a>
				</li>
				<li>
					<a href="/default.php?content=mold-help">MOLD HELP</a>
				</li>
				<li>
					<a href="/default.php?content=living-tiny">LIVING TINY</a>
				</li>
				<li>
					<a href="/default.php?content=comingsoon">MISSONS</a>
				</li>
				<li>
					<a href="/default.php?content=give">GIVE</a>
				</li>
				<li>
					<a href="/default.php?content=archive">ARCHIVE</a>
				</li>
			</ul>
		</li>
	</ul>
</div>
