<!--
		<h3>Recent Posts</h3>
		<ul id="leftContent">
			<li>
				<img class="newsImage" src="images/ywam-chico-entrance-sign.jpg" style="display:block;" width="100" />
				<a href="/default.php?content=newsletter&n=may-2014">The Ruda Journal: May 2014</a>
			</li>
			<li>
				<img class="newsImage" src="images/thumbs/journal-update-thumb2.jpg" style="display:block;" width="100" />
				<a href="/default.php?content=newsletter&n=june-2014">The Ruda Journal: June 2014</a>
			</li>
			<li>
				<a target="_top" style="border: 0 none;" href="http://www.gofundme.com/b1zte0?utm_medium=wdgt" title="Visit this page now."><img style="border: 0 none;" src="http://funds.gofundme.com/css/3.0_donate/mint/widget.png" style="width:100%;"></a>
			</li>
		<ul>
	-->

<!-- Begin MailChimp Signup Form -->
	<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup" style="background-color:black;text-align:center;">
<form action="//andiruda.us8.list-manage.com/subscribe/post?u=49885360296763a005b2ecc5b&amp;id=819d8871fd" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<label for="mce-EMAIL">Subscribe to our mailing list</label>
	<input style="width:70%" type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_49885360296763a005b2ecc5b_819d8871fd" tabindex="-1" value=""></div>
    <div class="clear"><input style="width:70%" type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->
	<?php include "/content/pages/updates.php"; ?>
	<!-- <p style="text-align:center;"><a target="_top" style="border: 0 none;" href="http://www.gofundme.com/b1zte0?utm_medium=wdgt" title="Visit this page now."><img style="border: 0 none;" src="http://funds.gofundme.com/css/3.0_donate/mint/widget.png" style="width:100%;"></a></p> -->
