<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>The Ruda Family Blog</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="copyright" content="2014 AndiRuda All Rights Reserved" />
    <meta name="author" content="AndiRuda" />
    <meta name="city" content="" />
    <meta name="country" content="" />
    <meta name="Distribution" content="Global" />
    <meta name="Rating" content="General" />
    <meta property="og:title" content="The Ruda Family" />
    <meta property="og:url" content="http://therudafamily.com/" />
    <meta property="og:site_name" content="The Ruda Family" />
    <meta property="og:image" content="http://therudafamily.com/images/og-image.jpg" />
    <!-- <meta property="og:image" content="http://therudafamily.com/images/og-ruda-logo.png" /> -->
    <meta property="og:description" content="The Ruda Family blog." />
    <meta name="Robots" content="INDEX,FOLLOW" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="/css/custom.css" media="screen" />
	<link href="http://fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>

	<!-- Colorbox -->
	<link rel="stylesheet" href="/js/colorbox/colorbox.css" />
	<script src="/js/colorbox/jquery.colorbox.js"></script>
	<script src="/src/includes/sharedJSLib.js"></script>
