<h1>Aug 2014 Update</h1>
<span class="caption right"><img src="/images/boys-getting-muddy-web.jpg" style="width:100%"/>The boys after playing in mud at the playground.  Shows the difference between our boys.</span>
<p>
	It is time for another update.  Just to warn you, this may turn into a long read.  God has been doing some much in our lives.  I want to start off by first thanking everyone that has partnered with us on this road.  You have enabled us to be here, I can't thank you enough.  The Lord is leading our family into a new season of victory and health.  We are so excited to be on this journey with you guys. 
</p>
<p>
	For the sake of clarity, I have decided to divide this newsletter up into the main areas of Ministry that God has called us to and give an update on each.
</p>
<ol>
	<li>Technology</li>
	<li>Worship</li>
	<li>Pioneering</li>
	<li>Family</li>
</ol>
<h2>Technology</h2>
<p>
	One of the biggest calls we feel God is leading us into is the in the area of technology.  I (Andi) have professional and amateur background in technology in many different areas.  On our arrival at the Youth With A Mission base here in Chico, CA where we are currently ministering, the first need to present itself to us was the lack of cell phone signal at the base. 
	<h4>Cell Tower</h4>	<span class="caption left"><img src="/images/solar-powered-cell-antenna-4.jpg" style="width:100%" />One of the antennas from the solar powered cell tower pointing down at the Hotel, the main building at the YWAM base.</span>
	The base is located deep inside a canyon, and the canyon walls surround the base on all sides.  As a result, no one at the base is able to get a cell signal.  We saw in immediate need, so we answered it.  We installed a solar powered cell repeater up the canyon wall to boost signal.  In basic terms, it is a simple installation with 2 antennas, one points to the nearest cell tower then "re-broadcasts" the signal down into the canyon.  It was basically an experiment that we funded ourselves.  It has been running strong for 5 months now.  The next stage is to expand it.  At the time, the only type of system we could afford to put in place was one that worked for only a limited frequency range, meaning for only Verizon's 4GLte.  We are getting ready to move the installation over to a more permanent structure at the top of the canyon wall as well as increase the capacity to run on ALL carriers and ALL frequencies.  There are roughly 60 people on staff and constant schools and conferences at the base here that have been without cell phones this whole time.  <br /><span class="addressBlock">Do we need cell phones to exist in order to do the ministries God has called us to?</span><br /><span class="addressBlock">Not really. </span><br /><span class="addressBlock">Do cell phones enable us to connect and reach people easier, shorten the time it takes to coordinate, and free up time that can be spent on ministry?</span><br /><span class="addressBlock">Absolutely.</span><br /> Please pray with us.  The last piece of the puzzle is funding.  We have everything ready to go, all that is left is to purchase the new equipment.
	<h4>Systems and Network Admin</h4><span class="caption right"><img src="/images/solar-cell-tower-compilition.jpg" style="width:100%" /><strong>TOP</strong> Close up on the solar panel which doubles as a heat shield, <strong>LEFT</strong> View from behind the solar installation, <strong>MIDDLE</strong> Picture of one of the two directional antenna, <strong>RIGHT</strong> View of the front of the solar panel</span>
	 Another need that presented itself as we came onto the base was the need for a systems and network administrator.  There are over 100 connected wireless devices and roughly as many wired devices on our network, all connected to a single T1 Line that runs out to the road.  So just to give some perspective, 50 people on the base connected to a network under 200 devices (Phones, laptops, desktops, a few are static IPs for printers), and all 50 users are sharing 1.5MB download and 1.5MB upload speed between all their devices.  It turns out to roughly 0.5MB down and up, which again translates into basic web browsing.  Say goodbye to YouTube, Skype, and trying to stream video online (Netflix).  Increasing the internet speed is an obstacle we are believing a miracle on, as there are no real solutions at this time, however improving network infrastructure to allow for maximum efficiency, that is just good stewardship and what I feel I can contribute to this base.  Since arriving at this base I have been working towards just that.  This last month I have been going through the crazy network doing some mapping and replacing old computers with new computers recently donated to the base. <br />
	<h4>International Christian School</h4>
	<span class="caption left"><img src="/images/ICS-classroom.jpg" style="width:100%" />The classroom for our ICS kids grades 7-12.</span>
	The base here has an International Christian School as one of its ministries.  They have around 30 students (K-12), and their whole curriculum is on the computer.  Each year they have to uninstall and reinstall their educational software as well as upgrade all their virus definitions and windows updates need to be performed.   That is where I (Andi) come in.  I have been setting up these machines, and getting everything ready for school to start up in Sept.  This has been a great project for me to get up to my elbows in the network here.  The base, school building, and a majority of the outbuildings are around 100 years old.  The network that has been pieced together over the last 2 decades around the base has been a challenge to try and map.  When something goes down, for example, a router or switch, I am often-times, looking in walls and crawl spaces for a hub to reset, or a line that was chewed through.  
</p>
<h2>Worship</h2>
<p>
	When Rachel and I came to YWAM Chico under God's direction.  We weren't sure what he was going to have us do here or how we could help.  One area we felt a pull towards and an area God spoke directly to us about was the area of Music and Worship.  We both play and love to work with music and musicians.  In the middle of August we were approached and asked if we would lead worship on one of our weekly meetings!  God lead us to invite a few other people at the base to help us.  Come to find out each person that helped us in worship were people that had been discouraged by some incident in the past regarding worship and had then decided to close of to that area in their life because of the pain and hurt.  So we started practicing and just following the leadings of the Holy Spirit.  It was so amazing to see these people  that were carrying this discouragement and pain start to blossom as they activate and re-activate the gifting of worship.  The morning we lead worship wasn't the most amazing performance, but something unique happend.  I felt a shift in the atmosphere.  it felt as if the wind had been blowing one direction for a long time and all of the sudden there was a new direction it was blowing in.  I didn't really think much of it until the next day, which brought another worship session (YWAM Bases have a lot of prayer and worship meetings).  Halfway through worship the Holy Spirit showed up in power and began to move.  People started breaking through all the stuff of life and entering the attitude of worship to their creator!  A word that God had given Rachel when we were going to lead worship was to "Minister to the Lord".  That is exactly what happened.  It was as if we were before the throne of God and weren't just petitioning for our needs to be met, but we were joined with the eternal choir that continually without ceasing sings praises to our Lord enthroned.  It was an amazing time of worship the effect of which has lingered in the hearts of the people at this base.  Awakening vision and courage to pursue and hear the word of God.
	<h4>Music Lessons</h4><span class="caption right"><img src="/images/rachel-teach-piano.jpg" style="width:100%;" />Rachel teaching piano to an aspiring student</span>
	Rachel has been giving guitar and music lessons to a teen on the base.  We didn't realize just how much God wanted to utilize our gifts or how much desire there was for music at this base.  There are many talented and aspiring musicians and worshipers.  It feels like a pile of sticks that is ready for a bonfire, all that is needed is the match.  After we finally got settled in our house we were able to get Rachel's piano up and in place so that she can now give piano lessons to the kids that have been inquiring, instead of just guitar lessons.
	<h4>School of Worship</h4><span class="caption left"><img src="/images/boys-and-umbrellas-web.jpg" style="width:100%;" />The boys holding umbrellas for a couple friends after a very rare rain storm</span>
	The school of Worship is slated to start this upcoming February.  We are getting excited and geared up for it.  We already have a few student applications in for it.  What we are in desperate need of is Staff applications.  Particularly a school leader.  With YWAM, there is the ability to offer accredited courses as long as you setup your school through the University Of The Nations, in order for YWAM Chico to launch this School of Worship as a  class through the U of N, we need an accredited school leader.  Rachel has gone through a School of Worship , but she is not qualified to be a school leader.  Please pray with us for God to send us a School leader with the qualifications to lead the School of Worship so that our students will be able to receive credits through YWAM Chico.  Rachel will be staffing the course, and I (Andi) will be playing stay at home dad during that time.  
	<h4>Base Worship</h4>
	We have been getting involved in the base worship that happens weekly.   I (Andi) just lead the first worship for the new Discipleship Training Course that has just started up for the fall.  It was an amazing time.  Rachel lead base worship a few weeks prior to that as well in a holy spirit encountering service.  We are so excited to be a part of worship at this base.
</p>

<h2>YWAM Pioneering</h2><span class="caption right"><img src="/images/YWAM-bend.jpg" style="width:100%;" />New YWAM base starting up in Bend, OR</span>
<p>
	We were living in Bend last summer when we found out that there was a group of people wanting to pioneer a YWAM base in Bend, OR.  We prayed about partnering with them.  We knew we wanted to be apart of starting a base in Bend, we just weren't sure if we could.  We were still healing up and still figuring life out, and it was still another year until the base was scheduled to start.  We met with half of the group from Idaho that was going to pioneer the base with another family.  We fell in love with them and their vision.  Not knowing what the future was going to hold for us we committed to praying for the upcoming base and helping in anyway that we were able to.<br /><br />
	Now fast forward to current.  We are in YWAM Chico, and the time has come for the base to start up.  We are currently committed to this base for the next 2 years, but we are still committed to helping pioneer YWAM Bend.  So, how does that look?  At the end of Aug, we did a conference call with the group starting YWAM Bend.  Among the many things we talked about, we found out they need a website, which I (Andi ) will be helping with.  We also found out they are doing a cruise and they need someone to lead worship durring the community gatherings they have scheduled on the cruise, which happens to be one of Rachel's gifting.  Finally we will be making trips up there and hope to better create ties between these bases that are only hours apart.
</p>
<h2>Family</h2>
<p>
	<h4>Health</h4>
	Finally to update everyone on how the Ruda family is doing.  Health wise we are continuing to get prayer and healing over our immune systems and nervous systems.  We have had a few setbacks with mold encounters in the homes and buildings around the base here, but we are progressing forward.  We are not victims, but victors!  We found out a few months ago that Isaac had a cavity in pretty much each one of his baby teeth.  Some are worst then others.  I was finally able to get the boys on insurance and that has covered the dental work we have done so far.  We have 6 more teeth to get crowned or filled and they want to have Isaac put under as the amount of work is too extensive for a few visits and might be a bit too much for a 4 year old boy.  We have agreed, and are setting up an appointment time.  The insurance will cover all but $600 for the anesthesiologist.  Please be praying for God's financial provision.  If you are interested in giving to help us meet this financial need, please visit the <a href="/default.asp?content=give">Giving Page</a>.  <br /><br />
	<h4>Housing</h4>
	We were living in our tiny home as volunteers here on the base while we were praying about becoming staff.  After we applied for staff the base started searching the accommodations that would suit our family and needs around the campus.  While we were blessed and loved our tiny home on a trailer, and were going to be sad to let go of it, we felt it was time for a little more space.  The base found a home that needs a little TLC, but it is dry and big.  We moved into our new home at the end of August.  We are loving it here!  The boys have their own room <strong>and</strong> a play room.  Rachel and I have our own room with a door!  We are so thankful for the way God has provider for us durring a challenging time.  Thank you everyone for you prayers and support.  <br /><br />
	<h4>Truck</h4>
	God has blessed us with an amazing truck for a super great price.  The truck has been running like a champ for the whole time we have owned it.  When we pulled our tiny home over the mountain pass on the border of California and Oregon the radiator started leaking.  As a quick fix I poured some stop leak into it to get us to YWAM Chico, knowing that some time down the line I would have to replace the radiator and possible other portions of the cooling system.  That time has come.  We loaned the truck to another couple on the base for a town run, and on their way back the water pump finally gave out.  We were amazed to find out the cost of the new pump and radiotor was what we had in our savings fund.  We were able to get a ride into town that weekend, pick up all the parts, and with the help of another guy on the base here, replaced the radiotor, water pump, and thermostat all in one weekend!  <br /><br />
	We thank God for you guys and the relationships we have been able to build with each of you.